os:
  - linux
  - osx
language: node_js
node_js:
  # Note: older node versions fail on a regex flag and/or async/await
  # - "4"
  # - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "node"
script:
  - npm run vuln-scan
  - npm test
sudo: false
before_install:
  - "mkdir -p ./git/hooks"